@startuml
!theme vibrant
scale 2

package "クライアント" {
  [クライアントGUI]
  [ソケット通信]
}

package "サーバー" {
  [サーバーGUI]
  [接続管理]
  [ファイル管理]
}

[クライアントGUI] -- [ソケット通信]
[ソケット通信] -- [接続管理] : TCP/IP
[接続管理] -- [サーバーGUI] : ログ表示
[接続管理] -- [ファイル管理]

@enduml
